const $=s=>document.querySelector(s), money=n=>new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n), titles=['Choose your model','Build your workstation','Complete your spray system','Choose your spray tool','Finish your setup','Make it yours','Filter care','Your quotation'];
let state={model:1,accessoryModel:1,support:'none',spray:false,gun:'none',extras:[],personal:false,filters:[]},step=0,logo='',lead={},reference='';
try{const saved=JSON.parse(localStorage.getItem('chococabin-build'));if(saved&&Number.isInteger(saved.model)&&(CATALOG.models[saved.model]||saved.model===-1))state={...state,...saved,extras:(saved.extras||[]).filter(x=>CATALOG.extras.some(e=>e.id===x))};}catch{}
if(state.support==='support')state.support=state.model===0?'bayonet':'tray';
const accessoriesOnly=()=>state.model===-1;
const compatibilityModel=()=>accessoriesOnly()?state.accessoryModel:state.model;
const activeSteps=()=>accessoriesOnly()?[0,1,2,3,4,6,7]:[0,1,2,3,4,5,6,7];
const availableSupports=()=>CATALOG.supports.filter(s=>s.models.includes(compatibilityModel()));
const selectedSupport=()=>availableSupports().find(s=>s.id===state.support);
const availableFilters=()=>CATALOG.filterOptions[compatibilityModel()===0?'small':compatibilityModel()===3?'l200':'large'];
function normalizeConfiguration(){
 if(!CATALOG.models[state.accessoryModel])state.accessoryModel=1;
 if(accessoriesOnly())state.personal=false;
 if(state.support!=='hot'&&!selectedSupport()&&!(accessoriesOnly()&&state.support==='none'))state.support=accessoriesOnly()?'none':'hot';
 if(!Array.isArray(state.filters))state.filters=state.filters?availableFilters().map(f=>f.id):[];
 state.filters=state.filters.filter(id=>availableFilters().some(f=>f.id===id));
}
normalizeConfiguration();
const model=()=>CATALOG.models[compatibilityModel()];
function lines(){let a=accessoriesOnly()?[]:[{name:'CHOCOCABIN '+model().name,price:model().price}];if(state.support!=='none')a.push({name:(state.support==='hot'?'Hot Storage':selectedSupport()?.name||'Support')+' — '+model().name,price:state.support==='hot'?(compatibilityModel()===0?CATALOG.prices.hotSmall:CATALOG.prices.hotLarge):selectedSupport()?.price||0});if(state.spray)a.push({name:'Chokompressor '+model().compressor+' L',price:model().compressorPrice},{name:'Walker filtration',price:CATALOG.prices.walker});if(state.gun!=='none')a.push({name:'SATA Ø'+state.gun+' mm',price:CATALOG.prices.gun});if(state.spray||state.gun!=='none')a.push({name:'Hose + connection kit (required)',price:CATALOG.prices.connections});CATALOG.extras.filter(e=>state.extras.includes(e.id)).forEach(e=>a.push(e));if(state.personal)a.push({name:'Custom screen printing',price:CATALOG.prices.personalization});availableFilters().filter(f=>state.filters.includes(f.id)).forEach(f=>a.push({name:f.name+(compatibilityModel()===0?'':' — '+model().name)+' ('+f.detail+')',price:f.price}));return a;}
const total=()=>lines().reduce((s,l)=>s+l.price,0);
$('#models').innerHTML=CATALOG.models.map((m,i)=>`<article class="model"><div class="image"><img loading="lazy" src="assets/${m.image}.webp" alt="ChocoCabin ${m.name}"></div><h3>${m.name}</h3><p>${m.tag}</p><p>${m.dimensions}</p><button class="model-link" data-model="${i}">Configure ${m.name} <span>↗</span></button></article>`).join('');
function open(i){if(i!==undefined)state.model=i;step=0;$('#config').showModal();document.body.style.overflow='hidden';render();}
$('.config-head .brand').onclick=e=>e.preventDefault();document.querySelectorAll('.build').forEach(b=>b.onclick=()=>open());document.querySelectorAll('[data-model]').forEach(b=>b.onclick=()=>open(+b.dataset.model));$('#close').onclick=()=>$('#config').close();$('#config').addEventListener('close',()=>document.body.style.overflow='');$('#save').onclick=()=>{localStorage.setItem('chococabin-build',JSON.stringify(state));$('#save').textContent='Saved on this device ✓';setTimeout(()=>$('#save').textContent='Save build',2500)};
function option(value,title,desc,selected,image){return `<button class="option ${selected?'selected':''}" data-value="${value}">${image!==undefined?`<img src="assets/${image}.webp" alt="">`:''}${selected?'●':'○'} ${title}<small>${desc}</small></button>`;}
function render(){ normalizeConfiguration(); $('#next').style.display=''; $('#steps').innerHTML=titles.map((t,i)=>`<button ${accessoriesOnly()&&i===5?'hidden':''} class="${i===step?'active':''}" data-step="${i}">${String(i+1).padStart(2,'0')} / ${['Model','Workstation','Spray system','Spray tool','Accessories','Personalization','Filter care','Quotation'][i]}</button>`).join('');document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{step=+b.dataset.step;render()});$('#step-count').textContent=`${String(step+1).padStart(2,'0')} / 08`;$('#step-title').textContent=titles[step];$('#preview').src=accessoriesOnly()?'assets/accessories.png':`assets/${model().image}.webp`;$('#preview').alt=accessoriesOnly()?'Accessory preview':'Selected ChocoCabin model';$('#view-name').textContent=accessoriesOnly()?'Accessories only':'CHOCOCABIN '+model().name;$('#total').textContent=money(total());$('#back').disabled=step===0;$('#next').textContent=step===7?'Create quotation →':'Continue →';$('#personal-preview').innerHTML=state.personal&&logo?'<img alt="Your uploaded artwork preview">':'';if(state.personal&&logo)$('#personal-preview img').src=logo;
let componentIds=[];if(state.support==='hot')componentIds.push(compatibilityModel()===0?5:6);if(selectedSupport())componentIds.push(selectedSupport().image);if(state.spray)componentIds.push(7,8);if(state.gun!=='none')componentIds.push(9);CATALOG.extras.filter(x=>state.extras.includes(x.id)&&x.image!==undefined).forEach(x=>componentIds.push(x.image));availableFilters().filter(f=>state.filters.includes(f.id)&&f.image!==undefined).forEach(f=>componentIds.push(f.image));componentIds=[...new Set(componentIds)];$('#components').innerHTML=componentIds.map(i=>`<img src="assets/${i}.webp" alt="Selected component preview">`).join('');
let html='';if(step===0)html=CATALOG.models.map((m,i)=>option(i,m.name,`${m.dimensions} · ${money(m.price)}`,state.model===i)).join('')+option(-1,'None — accessories only','Choose accessories without purchasing a cabin.',accessoriesOnly());
if(step===1)html=(accessoriesOnly()?option('none','No workstation support','Choose only the accessories you need.',state.support==='none'):'')+option('hot','Hot Storage '+model().name,`Heated storage · ${money(compatibilityModel()===0?CATALOG.prices.hotSmall:CATALOG.prices.hotLarge)}`,state.support==='hot',compatibilityModel()===0?5:6)+availableSupports().map(s=>option(s.id,s.name+' — '+model().name,`${compatibilityModel()===0?'Bayonet rotating stand and compressor support':'40 × 60 tray support and compressor support'} · Demo price ${money(s.price)}`,state.support===s.id,s.image)).join('');
if(step===2)html=option('own','I have my own equipment','Keep your existing spraying setup.',!state.spray)+option('full','Complete my spraying setup',`Chokompressor ${model().compressor} L + Walker filtration + connections · ${money(model().compressorPrice+890+120)}`,state.spray,7);
if(step===3)html=option('none','No spray gun','Continue with your existing tools.',state.gun==='none')+['1.0','1.6','2.0'].map((n,i)=>option(n,`SATA Ø${n} mm`,`${['Precision / delicate applications','Versatility / balanced coverage','Coverage / denser preparations'][i]} · ${money(690)}`,state.gun===n,9)).join('')+'<p class="small">Selecting a spray gun automatically includes the hose and connection kit. Only one kit is charged per configuration.</p>';
if(step===4)html=CATALOG.extras.map(e=>option(e.id,e.name,money(e.price),state.extras.includes(e.id),e.image)).join('');
if(step===5)html=option('standard','Original CHOCOCABIN','Standard branding.',!state.personal)+option('custom','Personalized',`Logo, graphic or signature · ${money(390)}`,state.personal)+(state.personal?'<label for="artwork">Upload artwork for a preview</label><input id="artwork" type="file" accept="image/png,image/jpeg,image/webp"><p class="small">PNG, JPG or WebP · Up to 5 MB. Preview is shown separately; final placement and vector production artwork are confirmed by the manufacturer. Artwork stays in this browser session.</p>':'');
if(step===6)html=option('no','No spare filters','Continue without extra replacement filters.',state.filters.length===0)+availableFilters().map(f=>option(f.id,f.name,`${f.detail} · Demo price ${money(f.price)}`,state.filters.includes(f.id),f.image)).join('')+'<p class="small">Spare filters for CHOCOCABIN '+model().name+'. Select each replacement stage you need. Replacement frequency depends on use.</p>';
if(step===7)html='<div class="notice">DEMO QUOTATION · Illustrative EUR prices. This prototype creates a local quotation summary; it does not send an order or contact request.</div><div id="quote-lines">'+lines().map(l=>`<div class="summary-row"><span>${l.name}</span><span>${money(l.price)}</span></div>`).join('')+'</div><form id="lead-form"><label for="company">Company *</label><input id="company" name="company" required autocomplete="organization"><label for="type">Customer type *</label><select id="type" name="type"><option>Pastry business</option><option>Academy</option><option>Distributor</option></select><label for="name">Full name *</label><input id="name" name="name" required autocomplete="name"><label for="email">Email *</label><input id="email" name="email" type="email" required autocomplete="email"><label for="phone">Telephone *</label><input id="phone" name="phone" type="tel" required autocomplete="tel"><label for="country">Destination country / territory *</label><select id="country" name="country" required><option value="">Select destination</option></select><label for="city">City *</label><input id="city" name="city" required autocomplete="address-level2"><label for="notes">Notes / custom request</label><textarea id="notes" name="notes" rows="3"></textarea></form>';
if(accessoriesOnly()&&[1,2,6].includes(step))html='<label for="accessory-model">Compatible with your existing ChocoCabin</label><select id="accessory-model">'+CATALOG.models.map((m,i)=>'<option value="'+i+'" '+(state.accessoryModel===i?'selected':'')+'>'+m.name+'</option>').join('')+'</select><p class="small">Select compatibility only. No cabin is included.</p>'+html;
$('#options').innerHTML=html;if($('#accessory-model'))$('#accessory-model').onchange=e=>{state.accessoryModel=+e.target.value;render()};if(step===7){const names=new Intl.DisplayNames(['en'],{type:'region'});let regions=[];for(let a=65;a<=90;a++)for(let b=65;b<=90;b++){const code=String.fromCharCode(a,b);const name=names.of(code);if(name!==code&&!['EU','UN','EZ','QO','XA','XB','ZZ'].includes(code))regions.push([code,name]);}regions.sort((a,b)=>a[1].localeCompare(b[1])).forEach(([code,name])=>$('#country').add(new Option(name,code)));Object.entries(lead).forEach(([k,v])=>{if($('#lead-form').elements[k])$('#lead-form').elements[k].value=v});}
document.querySelectorAll('[data-value]').forEach(b=>b.onclick=()=>{const v=b.dataset.value;if(step===0){if(+v===-1&&state.model!==-1){state.accessoryModel=state.model;state.support='none';state.personal=false;}state.model=+v;}if(step===1)state.support=v;if(step===2)state.spray=v==='full';if(step===3)state.gun=v;if(step===4)state.extras=state.extras.includes(v)?state.extras.filter(x=>x!==v):[...state.extras,v];if(step===5)state.personal=v==='custom';if(step===6)state.filters=v==='no'?[]:state.filters.includes(v)?state.filters.filter(id=>id!==v):[...state.filters,v];render()});if($('#artwork'))$('#artwork').onchange=e=>{const f=e.target.files[0];if(!f)return;if(f.size>5e6||!['image/png','image/jpeg','image/webp'].includes(f.type)){alert('Choose a PNG, JPG or WebP image under 5 MB.');return}if(logo)URL.revokeObjectURL(logo);logo=URL.createObjectURL(f);render()};}
$('#back').onclick=()=>{if(step>0){if(step===7)lead=Object.fromEntries(new FormData($('#lead-form')));step=activeSteps()[activeSteps().indexOf(step)-1];render()}};$('#next').onclick=()=>{if(step<7){step=activeSteps()[activeSteps().indexOf(step)+1];render();return}if(accessoriesOnly()&&lines().length===0){alert('Select at least one accessory before creating your quotation.');return}const f=$('#lead-form');if(!f.reportValidity())return;lead=Object.fromEntries(new FormData(f));reference='CC-DEMO-'+Date.now().toString(36).toUpperCase();showQuote()};
function showQuote(){const container=$('#options');container.innerHTML='<div class="eyebrow">CONFIGURATION READY</div><h2>Your ChocoCabin.</h2><p id="ref"></p><div id="final-lines"></div><div class="notice">Equipment estimate only. Tax, worldwide shipping, packaging, production artwork and final compatibility require manufacturer confirmation. No email has been sent.</div><button class="option" id="print">Print / Save as PDF ↗</button><button class="option" id="download">Download configuration JSON ↓</button><button class="option" id="edit">Edit customer details</button>';if(accessoriesOnly())container.querySelector('h2').textContent='Your accessories.';$('#ref').textContent=reference+' · '+lead.company;$('#final-lines').innerHTML=lines().map(l=>`<div class="summary-row"><span>${l.name}</span><span>${money(l.price)}</span></div>`).join('');$('#next').style.display='none';$('#edit').onclick=()=>{$('#next').style.display='';render()};$('#download').onclick=()=>{const blob=new Blob([JSON.stringify({reference,demo:true,currency:'EUR',configuration:state,items:lines(),equipmentTotal:total(),customer:lead},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=reference+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};$('#print').onclick=()=>{document.querySelector('.print-sheet')?.remove();const sheet=document.createElement('div');sheet.className='print-sheet';sheet.innerHTML='<img class="quote-logo" src="assets/logobogana.png" alt="Bogana Chococabin"><h2>Demo configuration quotation</h2><p class="customer"></p><img src="'+(accessoriesOnly()?'assets/accessories.png':'assets/'+model().image+'.webp')+'" alt="Product preview"><div>'+$('#final-lines').innerHTML+'</div><h2>Equipment estimate: '+money(total())+'</h2><p>Illustrative demo prices in EUR. Excludes tax, shipping and packaging. Compatibility and final artwork require manufacturer confirmation. No order has been placed.</p>';sheet.querySelector('.customer').textContent=reference+' | '+Object.values(lead).join(' | ');document.body.append(sheet);window.print()};}
$('#config').addEventListener('close',()=>$('#next').style.display='');
