(()=>{
const story=document.querySelector('#story'),stage=document.querySelector('.story-stage'),canvas=document.querySelector('#sequence'),poster=document.querySelector('.sequence-poster'),ctx=canvas.getContext('2d'),chapters=[...document.querySelectorAll('.story-chapter')],bar=document.querySelector('.story-track span'),counter=document.querySelector('#story-progress');
const count=89,frames=new Array(count),reduced=matchMedia('(prefers-reduced-motion: reduce)'),urls=Array.from({length:count},(_,i)=>`assets/sequence/${String(i).padStart(3,'0')}.webp`);let target=0,drawn=-1,raf=0,loaded=0,next=0,failed=0;
function draw(){if(!ctx)return;let index=target;if(!frames[index]){let distance=count;frames.forEach((frame,i)=>{if(frame&&Math.abs(i-target)<distance){distance=Math.abs(i-target);index=i}})}const im=frames[index];if(!im)return;const w=stage.clientWidth,h=stage.clientHeight,dpr=Math.min(devicePixelRatio||1,2);if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);drawn=-1}if(drawn===index)return;ctx.setTransform(dpr,0,0,dpr,0,0);const scale=Math.max(w/im.width,h/im.height),dw=im.width*scale,dh=im.height*scale;const left=w<700?(w-dw)*.24:(w-dw)*.5;ctx.drawImage(im,left,(h-dh)/2,dw,dh);drawn=index;poster.classList.add('loaded');}
function update(){raf=0;const distance=Math.max(1,story.offsetHeight-stage.clientHeight),progress=reduced.matches?1:Math.max(0,Math.min(1,-story.getBoundingClientRect().top/distance));target=Math.round(progress*(count-1));const chapter=Math.min(3,Math.floor(progress*4));chapters.forEach((el,i)=>{el.classList.toggle('visible',i===chapter);el.setAttribute('aria-hidden',i!==chapter);el.inert=i!==chapter});counter.textContent=`0${chapter+1} / 04`;bar.style.transform=`scaleX(${progress})`;draw();}
function schedule(){if(!raf)raf=requestAnimationFrame(update)}
function loadNext(){if(next>=count)return;const i=next++,im=new Image();im.onload=()=>{frames[i]=im;loaded++;schedule();loadNext();};im.onerror=()=>{failed++;loadNext();if(loaded+failed===count&&failed)document.querySelector('#sequence-status').textContent='CHOCOCABIN · PRODUCT STORY'};im.src=urls[i];}
// Four parallel requests keep decoding and download pressure bounded.
for(let i=0;i<4;i++)loadNext();addEventListener('scroll',schedule,{passive:true});addEventListener('resize',()=>{drawn=-1;schedule()});reduced.addEventListener('change',schedule);update();
})();
